name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: ./.github/actions/setup-terraform
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Prepare secret.auto.tfvars
        run: |
          cat <<-EOF > secret.auto.tfvars
            github_token             = "${{ secrets.PERSONAL_TOKEN }}"
            slack_verification_token = "${{ secrets.SLACK_VERIFICATION_TOKEN }}"
          EOF
      - name: Run terraform init
        run: terraform init
      - name: Run terraform apply
        run: terraform apply -auto-approve

  dispatch:
    runs-on: ubuntu-latest
    needs:
      - terraform-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dispatch event
        uses: kota65535/github-workflow-dispatch-slack-action@main
        with:
          workflow: do-something.yml
          inputs: '{"foo":"1","bar":"2"}'
          channel: github
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Dispatch event
        uses: kota65535/github-workflow-dispatch-slack-action@main
        with:
          workflow: do-something.yml
          channel: github
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
